### ISSUE TITLE
dicom_redact - save redaction rectangles to sidecar file

### ISSUE THREAD

**Issue by howff** [SMI/dicompixelanon#10]
See also https://git.ecdf.ed.ac.uk/SMI/service/-/issues/154

As part of the extraction pipeline researchers will require access to the list of rectangles that were redacted.

* add to a DICOM tag?
* add separate file to sit alongside the DICOM?
* report all rectangles in a single report file or database?

Possible options:
* add to Image Comments tag (0020,4000) but this may already be populated, and it's non-standard
* add a Private tag, but all private tags are removed by CTP so adding a new one would be confusing
* add to a Modified Attributes Sequence tag, but this isn't a perfect match to the intention of the tag
* DICOM-RT ROI, but this is a separate file
* Presentation State DICOM file, but this is a separate file
* Add an overlay with type "ROI" to be used as a mask, but this may be difficult for the user to use
* Save an additional file alongside the DICOM file, containing rectangles in JSON format
* Pass the rectangle onto the next stage of the extraction pipeline in a rabbitmq message

**Comment by rkm** [comment]
My preference would be to avoid adding anything directly to the DICOM metadata, for the reasons you've highlighted. Easiest to get us moving would likely be a single file containing all the rectangles for the cohort, but longer term we could look at generating sidecar files, either JSON or DIOCM (SR or segmentation as suggested by [Clunie](https://www.dclunie.com/papers/CMIMI_2018_David_Clunie_StandardizingAIAnnotationsDICOM.pdf))

**Comment by howff** [comment]
This has been implemented in https://github.com/SMI/dicompixelanon/commit/882590bde46325f20758cc180f76d28129605ed6

`dicom_pixel_anon.sh` writes `rectangles.csv` containing columns `filename,left,top,right,bottom,frame,overlay`
